//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.13 at 07:22:59 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://hotel.com/soap/api", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hotel.soap.api;
