global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rest-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rest-api:9080']

  - job_name: 'graphql-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['graphql-api:9081']

  - job_name: 'soap-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['soap-api:9082']

  - job_name: 'grpc-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['grpc-api:9083']